create table category(
cat_id int not null generated by default as identity primary key,
cat_name varchar(15) not null
);

alter table category add constraint uniquectm_const unique (cat_name);

insert into category(cat_name) values('Romance'), ('Thriller'), ('Sci-fi'), ('Fantasy'), ('Non Fiction'), ('History');

create type avail as enum('yes','no');

create table book(
isbn varchar(15) not null primary key,
title varchar(30) not null,
author varchar (50) not null,
description varchar(120),
category_id int not null,
pub_date date not null,
publisher varchar(30),
availability avail default 'yes',
foreign key(category_id) references category(cat_id));


insert into book values ('123456', 'Scala', 'Martin Odersky', 'Come and have fun with Scala', 5, '01-01-2018', 'OReilly', 'yes');

insert into book values ('4327843', '1984', 'George Orwell', 'Scary book light years ahead of its time', 3, '01-01-2019', 'Penguin', 'yes');

insert into book values ('3524635', 'Outlander', 'Diana Gabaldon', 'Amazing story, romance through times', 1, '10-07-1991', 'Delacorte Books', 'no');

insert into book values ('2333647', 'The Witcher', 'Andrzej Sapkowski', 'Follow a strange guy fighting creatures', 4, '08-16-1986', 'SuperNowa', 'yes');

--referential integrity
insert into book values ('2435346', 'Jane Eyre', 'Charlotte Bronte', 'Romantic story about a strong girl', 7, '05-07-1847', 'Smith, Elder and Co.', 'yes');


create table user_detail(
detail_id int primary key generated always as identity,
street varchar(20) not null,
city varchar(15)not null,
phone_number varchar(11),
emial varchar(30) not null,
DOB date);

create table lib_user(
user_id int generated by default as identity primary key,
first_name varchar(10) not null,
last_name varchar(15),
detail_id int,
foreign key(detail_id) references user_detail(detail_id));




insert into user_detail (street, city, phone_number, emial) values ('London Road', 'Brighton', '075564567', 'user1@email.com');

insert into user_detail (street, city, phone_number, emial) values ('Main Road', 'London', '07456465', 'user2@email.com');

insert into lib_user(first_name, last_name, detail_id) values ('Santa', 'Claus',1), ('Tooth', 'Fairy', 2);

create table loan(
loan_id int primary key generated always as identity,
loan_date date not null,
user_id int not null,
book_id varchar(15) not null,
expected_date date not null,
actual_date date,
fee int default 0,
foreign key (user_id) references lib_user(user_id),
foreign key (book_id) references book(isbn));


insert into loan(loan_date, user_id, book_id, expected_date) values ( now(), 2, '3524635', now() + interval '3 week' );



