create table category(
id int not null generated by default as identity primary key,
name varchar(15) not null
);

insert into category(name) values('Romance'), ('Thriller'), ('Sci-fi'), ('Fantasy'), ('Non Fiction'), ('History');

create table book(
isbn varchar(15) not null primary key,
title varchar(30) not null,
author varchar (50) not null,
description varchar(120),
category_id int not null,
pub_date date not null,
publisher varchar(30),
availability varchar(3),
foreign key(category_id) references category(id));

insert into book values ('123456', 'Scala', 'Martin Odersky', 'Come and have fun with Scala', 5, '01-01-2018', 'OReilly', 'yes');

insert into book values ('4327843', '1984', 'George Orwell', 'Scary book light years ahead of its time', 3, '01-01-2019', 'Penguin', 'yes');

insert into book values ('3524635', 'Outlander', 'Diana Gabaldon', 'Amazing story, romance through times', 1, '10-07-1991', 'Delacorte Books', 'no');

insert into book values ('2333647', 'The Witcher', 'Andrzej Sapkowski', 'Follow a strange guy fighting creatures', 4, '08-16-1986', 'SuperNowa', 'yes');
